package com.example.order_service.model;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Entity representing a product in the order system.
 *
 * <p>This class represents a product that can be ordered. Each product has a unique
 * identifier, a name, and a price. Products are managed in a centralized product catalog
 * and can be referenced by multiple orders.</p>
 *
 * <p>The product entity stores basic product information including the product ID,
 * name, price, and the timestamp when the product was added to the system. This entity
 * is used in the order processing system to maintain product references and validate
 * product availability.</p>
 *
 * @see OrderItem
 * @author Order Service Team
 * @version 1.0
 */
@Entity
@Getter
@Setter
@Table(name = "products")
public class Product {

    /**
     * The unique identifier for this product.
     *
     * <p>This is the primary key of the products table, generated automatically
     * using database identity columns (auto-increment).</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "product_id")
    private Long productId;

    /**
     * The name of this product.
     *
     * <p>A descriptive name that identifies the product. This field is required
     * and must not be null.</p>
     */
    @Column(name = "product_name", nullable = false)
    private String productName;

    /**
     * The price of this product.
     *
     * <p>The selling price of the product stored as a BigDecimal for precise
     * monetary calculations. This field is required and must not be null.</p>
     */
    @Column(name = "price", nullable = false)
    private BigDecimal price;

    /**
     * The timestamp when this product was added to the system.
     *
     * <p>This field is automatically set to the current time when the product
     * is created and is useful for auditing and tracking product creation dates.</p>
     */
    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    /**
     * Default no-argument constructor.
     *
     * <p>Required by JPA for entity instantiation and by frameworks that use
     * reflection to create instances.</p>
     */
    public Product() {
    }

    /**
     * Constructor to create a Product with the specified name and price.
     *
     * <p>This constructor initializes a new product with the given product name
     * and price. The product ID will be generated by the database, and the
     * creation timestamp will be set to the current time.</p>
     *
     * @param productName the name of the product, must not be null
     * @param price the price of the product, must not be null
     */
    public Product(final String productName, final BigDecimal price) {
        this.productName = productName;
        this.price = price;
    }
}
