spring.application.name=payment-simulator

# Custom config
server.url=http://localhost:8083/
application.secret-key=truong123

# Spring web
server.port=8083

# ThymeLeaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
