apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order
data:
  application.properties: |
    spring.application.name=order-service

    # Custom config
    application.topic.order=order-events
    application.topic.inventory=inventory-events
    application.topic.payment=payment-events
    application.batch-size=10
    
    # postgres configuration
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=postgres

    # Spring JPA
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

    # Kafka server
    spring.kafka.bootstrap-servers=kafka-0.kafka-service.kafka.svc.cluster.local:9092

    # Kafka producer
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
    spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

    # Kafka consumer
    spring.kafka.consumer.group-id=inventory-group
    spring.kafka.consumer.auto-offset-reset=earliest
    spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
    spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
    spring.kafka.consumer.properties.spring.json.trusted.packages=*

    # Jackson
    spring.jackson.generator.write-bigdecimal-as-plain=true
    spring.jackson.deserialization.USE_BIG_DECIMAL_FOR_FLOATS=true
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-nodeport
  namespace: order
  labels:
    app: order-service
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: ${DOCKER_USERNAME}/order-service:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "Asia/Ho_Chi_Minh"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-0.postgres-service.order.svc.cluster.local:5432/order_db
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-db-secret
              key: password
        volumeMounts:
        # Mount the ConfigMap as a file in /config
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: order-service-config
