spring.application.name=inventory-service

server.port=8081

# Custom config
application.topic.order=order-events
application.topic.inventory=inventory-events
application.topic.payment=payment-events
application.batch-size=10

# postgres configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka consumer for OrderCreatedEvent
spring.kafka.bootstrap-servers=192.168.56.124:9092

# Kafka producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Kafka consumer
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Jackson
spring.jackson.generator.write-bigdecimal-as-plain=true
spring.jackson.deserialization.USE_BIG_DECIMAL_FOR_FLOATS=true