apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: inventory
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 
      targetPort: 5432 
  type: ClusterIP 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: inventory
spec:
  serviceName: "postgres-service" 
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "inventory_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: TZ
          value: "Asia/Ho_Chi_Minh"
        - name: POSTGRES_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret     
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pg-storage
          mountPath: /var/lib/postgresql/data 
  volumeClaimTemplates:
  - metadata:
      name: pg-storage
    spec:
      storageClassName: local-path
      accessModes: [ "ReadWriteOnce" ] 
      resources:
        requests:
          storage: 1Gi 